### ISSUE TITLE
Proposal: Drop elm- prefix from libraries

### ISSUE THREAD

**Issue by mgold** [elm-community/Manifesto#27]
`elm-commity/elm-random-extra`, for example, has `elm` in it twice. This convention was established before the community came along, and we wanted to be clear on our personal GitHub pages what the library we had created was for. Under elm-community, one assumes to find only Elm things, so it seems unnecessary.

Migrating is going to be a real pain - maybe it waits for 0.18 - but if I could wave a magic wand and remove the `elm-` prefix without any kind of legacy pain, would it be a good idea?

**Comment by JoeyEremondi** [comment]
My main hesitation is that this makes it awkward for anyone who forks a
project. It's clear what random is in Elm-community, but if I want to do a
PR, I now have JoeyEremondi/random in my personal github.
On May 13, 2016 6:53 PM, "Max Goldstein" notifications@github.com wrote:

elm-commity/elm-random-extra, for example, has elm in it twice. This
convention was established before the community came along, and we wanted
to be clear on our personal GitHub pages what the library we had created
was for. Under elm-community, one assumes to find only Elm things, so it
seems unnecessary.

Migrating is going to be a real pain - maybe it waits for 0.18 - but if I
could wave a magic wand and remove the elm- prefix without any kind of
legacy pain, would it be a good idea?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/elm-community/Manifesto/issues/27

**Comment by jvoigtlaender** [comment]
I agree with Max. Joey, you have the same problem with elm-lang/core, elm-lang/html etc.

**Comment by JoeyEremondi** [comment]
Very true, and I think it's even possible to change the repo name when you
fork. +1

**Comment by jvoigtlaender** [comment]
Actually: Why wait for 0.18? So far only 5 elm-community packages have been published in 0.17 versions. So maybe it's not too late to make the general name transition now for 0.17.

**Comment by mgold** [comment]
Okay, I'd like to wait for a few more people to weigh in, but I'm glad you two like the idea and I'll hold off publishing my e-c libs.

**Comment by lukewestby** [comment]
this sounds good to me, seeing elm- in front of every elm package ever is getting a little redundant

**Comment by ThomasWeiser** [comment]
I am also in favor of removing the tautologous _elm-_ prefixes.

**Comment by fredcy** [comment]
Sounds good to me.

**Comment by abadi199** [comment]
I'm also in favor of removing the _elm-_ prefixes, and we should just do it now for all unpublished packages, and for the one already published we can do what @rtfeldman suggested on [slack channel ](https://elmlang.slack.com/archives/elm-community/p1463243803000279)

**Comment by jvoigtlaender** [comment]
@abadi199, can you repeat here what the suggestion on the slack channel was? Or is it a secret? :smile:

**Comment by fredcy** [comment]
I believe this is the Slack conversation being referenced:

![screen shot 2016-05-17 at 8 55 09 am](https://cloud.githubusercontent.com/assets/15950/15324744/42c82834-1c0d-11e6-9a88-8f69444af2e0.png)

**Comment by abadi199** [comment]
Sorry, yes that's the slack conversation I was referring to.

**Comment by fredcy** [comment]
For packages already published such as elm-linear-algebra, are we to create a new renamed repo as a copy per rtfeldman's directions just above? If so, should we re-publish all the same versions?

**Comment by fredcy** [comment]
See also https://github.com/elm-community/elm-linear-algebra/issues/12

**Comment by lukewestby** [comment]
waiting on feedback to @fredcy's comments above for elm-community/elm-json-extra#11 as well

**Comment by abadi199** [comment]
I also need to know what to do for elm-community/elm-list-extra#43

I'm suggesting to add 

> DEPRECATED: Renamed to http://package.elm-lang.org/elm-community/[new-package-name]

to the Readme of the old package, and create a new repo with the new name, and reset the version to `1.0.0`

Also need to set the `elm-package.json` summary with the deprecate message so that it shows up in the search results summary in package.elm-lang.org.

e.g.:

``` json
{
    "version": "x.x.x",
    "summary": "DEPRECATED: Renamed to http://package.elm-lang.org/elm-community/[new-package-name]"
}
```

**Comment by jvoigtlaender** [comment]
Keeping a tally of which repositories haven't been renamed yet for some reason or another:
* https://github.com/elm-community/elm-linear-algebra - waiting on Evan to whitelist new name, https://github.com/elm-lang/package.elm-lang.org/pull/183
* https://github.com/elm-community/elm-webgl - waiting on the above
* https://github.com/elm-community/elm-material-icons - ?, maintainer @mgold 
* https://github.com/elm-community/elm-lazy-list - as above
* https://github.com/elm-community/elm-history - package set for deprecation?, https://github.com/elm-community/elm-history/issues/17#issuecomment-222337140, not updated for 0.17 yet
* https://github.com/elm-community/elm-number-format - package set for deprecation?, https://github.com/elm-community/elm-number-format/issues/7, not updated for 0.17 yet
* https://github.com/elm-community/elm-string-split - package set for deprecation?, https://github.com/elm-community/elm-string-split/issues/5, not updated for 0.17 yet
* https://github.com/elm-community/elm-function-extra - not updated for 0.17 yet
* https://github.com/elm-community/elm-http-extra - not updated for *0.16* (or even 0.15?) yet

**Comment by jvoigtlaender** [comment]
The following cases remain unaddressed here now:
* https://github.com/elm-community/elm-linear-algebra - waiting on @evancz to whitelist new name, https://github.com/elm-lang/package.elm-lang.org/pull/183
* https://github.com/elm-community/elm-webgl - waiting on the above
* https://github.com/elm-community/elm-material-icons - ?, maintainer @mgold

**Comment by jvoigtlaender** [comment]
Seems only one repository is left un-renamed: https://github.com/elm-community/elm-material-icons

After that, this issue could be closed @mgold?

**Comment by eeue56** [comment]
@mgold ping

**Comment by mgold** [comment]
Sorry! Will try to get to this.

**Comment by mgold** [comment]
[Done!](https://github.com/elm-community/material-icons)
