### ISSUE TITLE
Help migrate bogdanp's repos

### ISSUE THREAD

**Issue by eeue56** [elm-community/Manifesto#57]
@bogdanp

**Comment by Bogdanp** [comment]
What's the process for doing this?

**Comment by eeue56** [comment]
https://github.com/elm-community/Manifesto#renaming-elm-community-packages

tl;dr - Ideally

- Transfer your repos here
- Fork them back to your user (so that old versions of the package will work)

I'll handle the rest from there

**Comment by eeue56** [comment]
Transferred and forked back. Now to find maintainers!

**Comment by oldfartdeveloper** [comment]
@rgrempel or someone who can change ownership: @oldfartdeveloper needs to be added as an owner of the **elm-time** repo so that he can perform his maintainer duties.

**Comment by eeue56** [comment]
@oldfartdeveloper I've already done so. You need to accept the invite that I've sent - you probably need to check your email to find it, I think

**Comment by oldfartdeveloper** [comment]
@eeue56 You are correct; it's been so long I've forgotten that I have to respond to an email invite.  I did and everything's good.  Thanks!

**Comment by jvoigtlaender** [comment]
I'm noticing that these packages get added as `elm-combine`, `elm-time`, `elm-datepicker`.

Wasn't there consensus within the `elm-community` team that in most cases it makes sense to *not* have the `elm`-prefix on package names under `elm-community`, i.e., it should be `elm-community/datepicker` instead of `elm-community/elm-datepicker` etc.?

Now is the time to make sure that we don't get lots of repositories again that deviate from this consensus.

@elm-community/maintainers, @prikhi, @bbqbaron

**Comment by eeue56** [comment]
@jvoigtlaender I decided that the names here wouldn't make sense if they were just "time", for example. In fact, I think it would be better if they had a more unique name. "elm-jsone-xtra" makes sense to become "json-extra", but I'm less sure about "elm-time" becoming "time". More than happy to suggest dropping it, but I don't want to promote these libraries as the "correct" way of doing this in Elm.

**Comment by jvoigtlaender** [comment]
Yeah, I saw this being explicitly discussed for `route`, but not for `time`, `combine`, and `datepicker`. (And at least for `datepicker` I really don't see why the `elm`-prefix is needed).

**Comment by eeue56** [comment]
@jvoigtlaender Sorry, discussed with the maintainers on slack. That's my bad, should've done it on Github too

**Comment by jvoigtlaender** [comment]
> More than happy to suggest dropping it, but I don't want to promote these libraries as the "correct" way of doing this in Elm.

Hmm, I don't understand how having the `elm`- prefix or not having it relays any message about whether a given library is the "correct" way of doing things.

Does `elm-community/datepicker` in any way sound more official than `elm-community/elm-datepicker`? In other words, does calling the package `elm-datepicker` instead of `datepicker` really suggest that it's "less official"?

**Comment by eeue56** [comment]
@jvoigtlaender It was more thinking along the lines of "I don't think this is the right name for the package - so let's make the migration from bogdan's packages to elm-community's smooth, then move to a slightly different name that is more distinct". Thoughts?

**Comment by jvoigtlaender** [comment]
Makes sense.

**Comment by oldfartdeveloper** [comment]
@jvoigtlaender @eeue56 as the new maintainer for elm-time, I'm sympathetic to drop the "elm-" in the name, but I'm sympathetic to @eeue56 concerns.

That being said, how much of a burden is it on our developers to change the name of a package within **elm-community**?

I've also opened a **[new issue](https://egithub.com/elm-community/elm-time/issues/17)** inviting comments/concerns/ideas on **elm-time**'s API in general before actually publishing so that we don't launch with anything to regret.

**Comment by eeue56** [comment]
@oldfartdeveloper renaming things if they are published is actually quite a pain. Usually we take care of it during Elm version upgrades (e.g 0.17 -> 0.18). To understand some of the pain, see https://github.com/elm-community/Manifesto/issues/41
