### ISSUE TITLE
Add a DateTime package?

### ISSUE THREAD

**Issue by fredcy** [elm-community/Manifesto#7]
There has been discussion on elmlang.slack.com about putting a DateTime package on elm-community. That makes sense to me and I hope that would be a stepping stone to getting solid DateTime functionality into packages.elm-lang. Thinking of my Python experience with custom web apps, the datetime packages are essential and among my most-used.

So, does this make sense and, if so, what is the next step?

**Comment by mgold** [comment]
Hmm, this would be the first time the community would be writing a package from scratch, rather than maintaining one. The only time-related package out there is [mine](http://package.elm-lang.org/packages/mgold/elm-date-format/1.0.4/), for date and time formatting. If it could be expanded into something larger, I'm okay with the community taking it over. (If you just want to fix a bug or add more formatters, send a PR.)

Exactly what sort of date and time functionality do you have in mind? Maybe we should wrap [moment.js](https://github.com/moment/moment/)?

**Comment by lukewestby** [comment]
I started the conversation from looking into reimplementing Moment in Elm since there seems to be some demand, and it became apparent pretty quickly that doing so would amount to building a new DateTime package entirely. I was going to start on my own but figured a community driven effort would be more thorough and result in higher quality.

**Comment by lukewestby** [comment]
Hey folks, any thoughts on what we should plan to do? I have some time the next couple of days that I was hoping to spend on this. I can start things off in my own repo and add folks as they express interest and we can move it over here later if we're not ready to begin a project in elm-community. I figure there probably needs to be some amount of discussion about what it would look like to start a project, around licensing and all that. I know it's a busy time right now so I'll hold off on doing anything until I hear back :smile: thanks!

**Comment by mgold** [comment]
Why don't you go ahead and try to write the package on your own? At the very least you can report back with what _didn't_ work. You can also try to come up with a desired list of features, or an API even if it's unimplemented.

**Comment by lukewestby** [comment]
Sweet! Thanks @mgold for the quick response. I've got a nice 12-hour car ride to build things out tomorrow so I'll report back this weekend with some results. Would either you or @fredcy like to be added to the repo?

**Comment by lukewestby** [comment]
this can probably be closed, https://github.com/rluiten/elm-date-extra takes care of all of this

**Comment by fredcy** [comment]
It does look like elm-date-extra has this covered, so I'm closing this.
